version: '3'

services:


  phpapache:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html
      #- ./confg:/etc/apache2 // no funciona s'ha de fer copy
    env_file:
      - .env
    ports:
      - "80:80"
      - "8000:8000"
    

  mariadb: #Es el CONTAINERNAME
    image: mariadb:10.7
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    volumes:
      - ./importBBDD:/docker-entrypoint-initdb.d 
      - ./baseDades:/var/lib/mysql
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=${CONTAINERNAME}
    expose:
      - 8083
    ports:
      - 8083:80
  



  
